import type { Metadata } from 'next';
import { Maven_Pro } from 'next/font/google';
import './globals.css';
import Wrapper from '@/components/shared/wrapper';

const inter = Maven_Pro({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900', '600', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
