import type { Metadata } from 'next';
import { Maven_Pro } from 'next/font/google';
import './globals.css';
import Wrapper from '@/components/shared/wrapper';
import Footer from '@/components/footer/Footer';

const inter = Maven_Pro({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900', '600', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: '#090909',
        }}
      >
        <Wrapper>{children}</Wrapper>
        <Footer />
      </body>
    </html>
  );
}
